# Generated by Django 4.1.2 on 2023-02-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
    ]
